Javascript/javascript2/week2
pattnaikupasana/Learning-activities pull request #13
Opened 2022-09-05 06:02 UTC by pattnaikupasana

js2 week2 homework

2022-10-09 14:06 UTC, mutaquihadev requested changes
First congratulations for the great work.
I really like the way you use clear variable names.
The other nice thing to see is how well the code is organised and also your knowledge about array functions like filter, map, reduce.

Good work.
I have some minor suggestions, as soon as you implement them I will approve your PR.

2022-10-09 14:06 UTC, mutaquihadev commented on javascript/javascript2/week2/hyf-bay/hyfBayHelpers.js
> +    /* DONT MODIFY ANY OF THIS CODE!!!*/
May I ask why this coment is here?

2022-10-09 14:06 UTC, mutaquihadev commented on javascript/javascript2/week2/hyf-bay/hyfBayHelpers.js
> +        const name = getRandomProductname();
I would try to be consistent with the object creation. You've decided to declare a variable called name and later use the variable to attribute to a property inside the object. This is good because the code is more readable.

I would do the same with price, ratings and shipsTo.

2022-10-09 14:06 UTC, mutaquihadev commented on javascript/javascript2/week2/script1.js
> +console.log("The doubled numbers are", newNumbersDouble);
Could you elaborate a bit more about what was the goal of this exercise?
If doubling was the final goal, could you try to refactor and use just mapping instead of filter also?

2022-10-12 20:11 UTC, pattnaikupasana commented on javascript/javascript2/week2/hyf-bay/hyfBayHelpers.js
> +    /* DONT MODIFY ANY OF THIS CODE!!!*/
This comment is mentioned in hyfBayHelpers.js file which given in the Homework

2022-10-12 20:12 UTC, pattnaikupasana commented on javascript/javascript2/week2/hyf-bay/hyfBayHelpers.js
> +        const name = getRandomProductname();
Thank you i will remember

2022-10-12 20:13 UTC, merged