Javascript/javascript3/week1
pattnaikupasana/Learning-activities pull request #15
Opened 2022-11-03 17:18 UTC by pattnaikupasana

2022-11-14 18:10 UTC, materialsmoke commented
just for your information, in our company, we can't send a PR with commented code.
you can write comments. but you can't comment a block code and make PR.
=======
I couldn't understand why you have a lot of files in one PR!
can you fix your PR?
I don't think this one is acceptable, you made PR including week one and week 2 altogether.

2022-11-16 09:09 UTC, MartinLupa commented on javascript/javascript3/week1/gify.html
> +    <div class="gifSearchBar">
Class naming conventions: please change the corresponding class names to adopt a unified criteria.
If you adopt a hyphen separator like "gif-search-bar" it helps readability as CSS properties follow this convention (example: background-color, font-size).

You can check material like (https://www.freecodecamp.org/news/css-naming-conventions-that-will-save-you-hours-of-debugging-35cea737d849/).

2022-11-16 09:16 UTC, MartinLupa commented on javascript/javascript3/week1/gify.js
> +const searchButton = document.querySelector('button');
It is always better to have specificity in the selectors since it will make your code more maintainable. This button has a unique id attribute that you can use to select it ("#search-button". By selecting a unique id, or class, you can add another button to your code in the future without the risk of changing the expected behavior.

2022-11-16 09:24 UTC, MartinLupa commented on javascript/javascript3/week1/gify.html
> +        <div class="searchGifName">
classes searchGifName and numberOfgif are not used. It is always better to keep the code as clean as possible and remove unused elements.

2022-11-16 09:32 UTC, MartinLupa commented on javascript/javascript3/week1/gify.js
> +            .then((gifdata) => {
Please check the indentation in this block.
![image](https://user-images.githubusercontent.com/80256770/202142744-02c10476-67b5-4784-a72d-e7f72c868dc5.png)

2022-11-16 09:48 UTC, MartinLupa commented on javascript/javascript3/week1/gify.css
> +.input-name {
.input-name and .input-number have exactly the same properties. This could be refactored into only one comprehensive class including both inputs and save some lines of code.

2022-11-16 09:51 UTC, MartinLupa commented on javascript/javascript3/week1/weather.js
> +let weather = {
let could be const

2022-11-16 09:59 UTC, MartinLupa commented on javascript/javascript3/week1/weather.js
> +    apiKey: "157adfe4a239b55737c9ac5e809d7463",
In the future, you can check on the use of environment variables for API keys (.env files). These are a way of protecting them, since in most cases API keys are secret and personal (even more important if that API is a pay-per-use one). No need to implement now, just a friendly idea of improvement.

Recommended: https://www.codementor.io/@parthibakumarmurugesan/what-is-env-how-to-set-up-and-run-a-env-file-in-node-1pnyxw9yxj

2022-11-16 10:00 UTC, MartinLupa requested changes
Very well done! It was fun to check the weather in my home city in Argentina. 
As one of the mentors commented previously, please try to keep your branches clean and only include the corresponding exercises.
Please go ahead and implement the changes.

2023-01-17 13:12 UTC, merged